import { useSyncExternalStore } from 'react'
import { registerSW } from 'virtual:pwa-register'

/**
 * The service worker (generated by vite-plugin-pwa, see vite.config.ts). It
 * precaches the built shell so the app opens offline and starts instantly once
 * installed. A new build does not take over on its own: the worker waits, the
 * app shows "a new version is ready" (`useUpdateReady`) and the user applies it
 * with a tap (`applyUpdate`), which reloads the page onto the new bundles.
 *
 * In `npm run dev` the virtual module is a stub and none of this runs.
 */

const CHECK_EVERY_MS = 60 * 60 * 1000

let ready = false
let update: ((reloadPage?: boolean) => Promise<void>) | null = null
const listeners = new Set<() => void>()

function subscribe(listener: () => void) {
  listeners.add(listener)
  return () => {
    listeners.delete(listener)
  }
}

/** Registers the worker once; call from main.tsx. */
export function startServiceWorker() {
  if (!('serviceWorker' in navigator)) return
  update = registerSW({
    onNeedRefresh() {
      ready = true
      listeners.forEach((l) => l())
    },
    onRegisteredSW(_url, registration) {
      if (!registration) return
      // An installed app can stay open for days, so ask for a new build every
      // hour and whenever the app comes back to the foreground.
      const check = () => {
        if (document.visibilityState === 'visible' && navigator.onLine) registration.update().catch(() => {})
      }
      setInterval(check, CHECK_EVERY_MS)
      document.addEventListener('visibilitychange', check)
    },
  })
}

/** True once a newer build is installed and waiting. */
export function useUpdateReady(): boolean {
  return useSyncExternalStore(
    subscribe,
    () => ready,
    () => false,
  )
}

/**
 * Hands the page over to the waiting build and reloads onto it. The reload is
 * ours: the plugin only reloads when a worker already controlled the page at
 * registration, which is false on a first visit, and a tap must never do
 * nothing. `clientsClaim` (vite.config.ts) makes the new worker take the page,
 * which is what fires `controllerchange` here.
 */
export function applyUpdate() {
  if (!update) return
  navigator.serviceWorker.addEventListener('controllerchange', () => window.location.reload(), { once: true })
  void update()
}
